services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      #atenção estva POSTGRESL,  e é sem L  no final
      POSTGRES_DB: atelie
      POSTGRES_USER: atelie_user
      POSTGRES_PASSWORD: atelie_pass
      
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atelie_user -d atelie"]
      interval: 5s
      retries: 10
      timeout: 3s

  web:
    container_name: web
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
    # Mostra qual database da api o sqlalchemy deve importar, neste caso será bd postgres e psycop2
      DATABASE_URL: postgresql+psycopg2://atelie_user:atelie_pass@db:5432/atelie
      FLASK_ENV: development

volumes:
  postgres_data:
    driver: local

#docker-compose.yaml

#psycopg2 - drive oficial que conecta .py ao postgres. Gera instruções como CREATE TABLE, por exemplo. 
#DBAPI é Database da api - padrão .py PEP249, define como as bibliotecas de banco de dados irão se comportar (connect(), cursor() - prepara os comandos SQL, execute(), fetchone()/ fetchall() - busca resultados, é como um interface)
#DBAPI Drive é a biblioteca, é aponte entre .py e banco de dados